version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: rinha_backend_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha_backend
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql


volumes:
  postgres_data:
