version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: rinha_backend_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha_backend
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

#    # Server service
#  api1:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: api1_container
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    environment:
#      DB_URL: jdbc:postgresql://db:5432/rinha_backend
#      DB_USERNAME: postgres
#      DB_PASSWORD: postgres
#      DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect

volumes:
  postgres_data:
